-- MySQL Script generated by MySQL Workbench
-- Sat Apr  1 12:54:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema freedb_CoolProjectDb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `freedb_CoolProjectDb` ;

-- -----------------------------------------------------
-- Schema freedb_CoolProjectDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `freedb_CoolProjectDb` DEFAULT CHARACTER SET utf8 ;
USE `freedb_CoolProjectDb` ;

-- -----------------------------------------------------
-- Table `freedb_CoolProjectDb`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freedb_CoolProjectDb`.`autor` ;

CREATE TABLE IF NOT EXISTS `freedb_CoolProjectDb`.`autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `autor` VARCHAR(150) NOT NULL,
  `job` VARCHAR(100) NOT NULL,
  `image` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedb_CoolProjectDb`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freedb_CoolProjectDb`.`project` ;

CREATE TABLE `project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `slogan` VARCHAR(100) NOT NULL,
  `repo` VARCHAR(1024) NOT NULL,
  `demo` VARCHAR(1024) NOT NULL,
  `technologies` VARCHAR(150) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `photo` VARCHAR(1024) NOT NULL,
  `fkidproject` INT NOT NULL,
  PRIMARY KEY (`idProject`),
  KEY `fkidproject` (`fkidproject`),
  CONSTRAINT `project_fk_1`
    FOREIGN KEY (`fkidproject`)
    REFERENCES `project`(`idProject`)
  )
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO autor (autor,job, image) VALUES ('Josefina la Cerda', 'Full-Stack Developer', 'https://w7.pngwing.com/pngs/851/653/png-transparent-doll-drawing-doll-pic-miscellaneous-child-human.png'),
('Josefina', 'Full-Stack Developer', 'https://w7.pngwing.com/pngs/851/653/png-transparent-doll-drawing-doll-pic-miscellaneous-child-human.png'),
('Bob Esponja', 'Full-Stack Developer', 'https://w7.pngwing.com/pngs/851/653/png-transparent-doll-drawing-doll-pic-miscellaneous-child-human.png'),
('Patricio', 'Full-Stack Developer', 'https://w7.pngwing.com/pngs/851/653/png-transparent-doll-drawing-doll-pic-miscellaneous-child-human.png');

INSERT INTO project (name, slogan, repo, demo ,technologies, description, photo, fkidproject) VALUES ('Cool Project ladies', 'Guarda aquí tus proyecto!', 'https://github.com/Adalab/project-promo-s-module-4-team-4', 'http://beta.adalab.es/Project-promo-s-module-3-team-4/', 'React, SCSS', 'Proyecto en grupo creado como almacenaje de repositorios y webs creadas', 'https://coachready.com/dev/wp-content/uploads/2015/09/nuevo-mundo-del-trabajo.jpg', 1),
('Cool Project ladies', 'Guarda aquí tus proyecto!', 'https://github.com/Adalab/project-promo-s-module-4-team-4', 'http://beta.adalab.es/Project-promo-s-module-3-team-4/', 'React, SCSS', 'Proyecto en grupo creado como almacenaje de repositorios y webs creadas', 'https://coachready.com/dev/wp-content/uploads/2015/09/nuevo-mundo-del-trabajo.jpg', 2),
('Cool Project ladies', 'Guarda aquí tus proyecto!', 'https://github.com/Adalab/project-promo-s-module-4-team-4', 'http://beta.adalab.es/Project-promo-s-module-3-team-4/', 'React, SCSS', 'Proyecto en grupo creado como almacenaje de repositorios y webs creadas', 'https://coachready.com/dev/wp-content/uploads/2015/09/nuevo-mundo-del-trabajo.jpg', 3),
('Cool Project ladies', 'Guarda aquí tus proyecto!', 'https://github.com/Adalab/project-promo-s-module-4-team-4', 'http://beta.adalab.es/Project-promo-s-module-3-team-4/', 'React, SCSS', 'Proyecto en grupo creado como almacenaje de repositorios y webs creadas', 'https://coachready.com/dev/wp-content/uploads/2015/09/nuevo-mundo-del-trabajo.jpg', 4);

SELECT * FROM autor;
SELECT * FROM project;

SELECT autor.autor, autor.job, autor.image, project.name, project.slogan, project.repo, project.demo, project.technologies, project.description, project.photo 
FROM autor INNER JOIN project ON autor.idautor = project.fkidproject 
WHERE autor.idautor = 3;
