-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 13:32:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autor` ;

CREATE TABLE IF NOT EXISTS `autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `autor` VARCHAR(150) NOT NULL,
  `job` VARCHAR(100) NOT NULL,
  `image` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

CREATE TABLE IF NOT EXISTS `project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `slogan` VARCHAR(100) NOT NULL,
  `repo` VARCHAR(1024) NOT NULL,
  `demo` VARCHAR(1024) NOT NULL,
  `technologies` VARCHAR(150) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `photo` VARCHAR(1024) NOT NULL,
  `autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`idProject`, `autor_idAutor`),
  INDEX `fk_project_autor_idx` (`autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_project_autor`
    FOREIGN KEY (`autor_idAutor`)
    REFERENCES `autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
